# -*- coding: utf-8 -*-
"""Day-7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LMKiMuiKnrf_eIRcLLJlPZDtObZGPbmE

**Enumeration()**
"""

supplies = ["tyu", "uyt", "uhg ", "iiui" ]
for index, item in enumerate(supplies):
  print("Index " + str(index) + "in supplies is: " + supplies[index])
for i in range(len(supplies)):
  print("Index " + str(i) + "in supplies is : " + supplies[i])

"""**Random_Selection_Ordering**"""

import random
pet = ["siga", "higa", "jiga", "kiga"]
random.shuffle(pet)
print(pet)
random.choice(pet)

"""**Augmented_Assignment_operator**"""

num = 12
num += 1
print(num)
num *= 2
print(num)
num / 5
print(num)
num -= 2
print(num)
num %= 3
print(num)

"""# **List_Methods**

**Finding_Values**
"""

spam = ["light", "sight", "hight" ," sight"]
print(spam[0])
spam.index("light")
spam.index("hight")
#Same two Items will give First One
spam.index("sight")
#not item will give error
#spam.index("sskks")

"""**Adding_Items**"""

spam = ["ghi", "hig"]
spam.append("fig")
spam.insert(1 , "did")
print(spam)

"""**Remove_Items**"""

name = ["mehtab", "ali", "siga" , 1, 1, 1, 1]
name.remove("ali")
print(name)

#Remove Those Items Which Are Not Present
#name.remove("sis")
print(name)

#If The Value Is Present Multipe Times
name.remove(1)
print(name)

"""**Sort_Items**"""

#Sort The List
spam = [3, 4, 8, 3, 98, 43, 1]
spam.sort()
print(spam)

#Sort Reverse
spam.sort(reverse=True)
print(spam)

#List With Mixed Values Can Be Sort
#spam = ['Alice', 'Bob', 'ants', 'badgers', 'Carol', 'cats', 1, 4, 2.2 ]
spam.sort()
print(spam)

names = ["ali", "Oli" , "ody", "Body"]
names.sort(key = str.lower)
print(names)

"""**Short-Circuiting Boolean Operators**"""

'''
spam = ["mehtab", "Ali"]
if spam[0] == 'mehtab':
  print("Present")
else:
  print("Absent")
'''
#Short_Circuiting

spam = []
if len(spam) > 0 and spam[0] == 'cat':
    print('A cat is the first item.')
else:
    print('The first item is not a cat.')

"""**A Short Program: Magic 8 Ball with a List**"""

import random

message = ["my name is mehtab",
           "my name is hamemd",
           "my name is javaria",
           "my name is usman",
           "my name is yousaf",
           "my name is ali"]
print("Enter to print message: ")
input(">")
print(message[random.randint(0, len(message) - 1)])

"""**Sequence Data Types**"""

name = "Mehtab ahmad khan"
print(name[0])
print(name[-2])
print(name[0:6])
print('Meh' in name)
print("fff" not in name)
for i in name:
  print("* * * " , i , " * * * ")