# -*- coding: utf-8 -*-
"""Day-9_Dictionaries.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mlMX0UdHiNOGVkhieOKt2Nc-GSNfcdXv

# **Dictionary_Data_Type**
"""

#Declare_data_Type

spam = {"name": "mehtab" , "age": 12 , "direction": "south"}
print(spam["age"])


#Number_As_Key

name = {1: "monday", 2: "tuesday", 3: "wednesday"}
print(name[1])

#Comparing_List_And_Dictionaries
new1 = ["god", "sod", "hig"]
new2 = ["sod", "hig", "god"]
new1 == new2
dic1 = {"god": 1, "sod": 2, "hig": 3}
dic2 = {"sod": 2, "hig": 3, "god": 1}
dic1 == dic2

#Program_For_Birthday

birthdays = {"mehtab": "33dec", "saood": "7feb", "ali": "8dec"}
while True:
  print("Enter a name: ")
  name = input()
  if name == "":
    break

  if name in birthdays:
    print(birthdays[name])

  else:
    print("You enter the wrong name")

#Program_For_Week

week = {1 : "Wednesday", 2: "monday", 3: "friday", 4: "saturday"}
while True:
    print("Enter week day For Printing day:  ")
    num = int(input())
    if num == 1:
      print(week[1])
    elif num == 2:
      print(week[2])
    elif num == 3:
      print(week[3])
    elif num == 0:
      break