# -*- coding: utf-8 -*-
"""Day-13_TEXT_PATTERN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1McVzbbryStj5d9wyRHJRISjoTm-j4G75

# **TEXT PATTERN MATCHING WITH REGULAR EXPRESSIONS**
"""

def is_phone_num(text):
  if len(text) != 12:
    return False
  for i in range(0,3):
      if not text[i].isdecimal():
        return False
  if text[3] != "-":
        return False
  for i in range(4 ,7):
    if not text[i].isdecimal():
      return False
  if text[7] != "-":
    return False
  for i in range(8, 12):
    if not text[i].isdecimal():
      return False
  return True
message = 'Call me at 415-555-1011 000-000-0000 tomorrow. 415-555-9999 is my office.'
for i in range(len(message)):
    segment = message[i:i+12]
    if is_phone_num(segment):
        print('Phone number found: ' + segment)
print('Done')

def is_phone_number(text):
    if len(text) != 12:  # Phone numbers have exactly 12 characters.
        return False
    for i in range(0, 3):  # The first three characters must be numbers.
        if not text[i].isdecimal():
            return False
    if text[3] != '-':  # The fourth character must be a dash.
        return False
    for i in range(4, 7): # The next three characters must be numbers.
        if not text[i].isdecimal():
            return False
    if text[7] != '-':  # The eighth character must be a dash.
        return False
    for i in range(8, 12):  # The next four characters must be numbers.
        if not text[i].isdecimal():
            return False
    return True
message = "my num is 000-123-2343"
for i in range(len(message)):
    segment = message[i:i+12]
    if is_phone_num(segment):
      print("Number found: " + segment)
print("Done")

print('Is 415-555-4242 a phone number?', is_phone_number('415-555-4242'))
print(is_phone_number('415-555-4242'))
print('Is Moshi moshi a phone number?', is_phone_number('Moshi moshi'))
print(is_phone_number('Moshi moshi'))

#checking_Pakistan_Number
def is_pak_num(text):
  if len(text) != 11:
    return False
  for i in range(0,3):
    if text[0:4] == "0314":
      return True
message = "my num is 03145099499 and my bro num is 03141234567"
for i in range(len(message)):
  segment = message[i: i+11]
  if is_pak_num(segment):
    print("Phone num found: " + segment)
print(is_pak_num("03142345611"))

"""Finding Text Patterns with Regular Expressions
**bold text**
"""

import re
phone_num_pattern_obj = re.compile(r'\d{3}-\d{3}-\d{4}')
num_obj = phone_num_pattern_obj.search("my number is 12345678912 and 123-123-1234")
num_obj.group()

"""**Grouping with Parentheses**"""

import re
#phone_num_pattern = re.compile(r'(\d{3})-(\d{3}-\d{4})')
phone_num_pattern = re.compile(r'(\d\d\d)-(\d\d\d-\d\d\d\d)')
mo = phone_num_pattern.search("my num is 123-456-7890")
mo.group()
mo.group(0)
mo.group(1)
mo.group(2)
area_code, main_number = mo.groups()
print(area_code)
print(main_number)

"""**Using Escape Characters**"""

import re
"""
pattern = re.compile(r"(\(\d\d\d\))-(\d\d\d-\d\d\d\d)")
mo = pattern.search("my num is (123)-123-2345")
mo.group()
mo.group(1)
mo.group(2)


other_patter = re.compile(r'(\*\d\d\d\*)-(\d\d\d-\d\d\d\d)')
mo2 = other_patter.search("my num is *123*123-2345")
mo.group()
"""
other_patter = re.compile(r'(\$\d\d\d\$)-(\d\d\d-\d\d\d\d)')
mo2 = other_patter.search("my num is $123$-123-2345")
mo.group()

pattern = re.compile(r'(\$\d\d\d\$) (\d\d\d-\d\d\d\d)')
mo = pattern.search('My phone number is $415$ 555-4242.')
mo.group(1)

mo.group(2)
mo.group()
#Can_Be_Used_For_$ () * + - . ? [\] ^ {|}
patter2 = re.compile(r'(\*\d\d\d\*) (\d\d\d-\d\d\d\d)')
mo2 = patter2.search("My number is *415* 555-4242")
mo2.group(1)
mo2.group()

patter3 = re.compile(r'(\?\d\d\d\?) (\d\d\d-\d\d\d\d)')
mo3 = patter3.search("My number is ?415? 555-4242")
mo3.group(1)
mo3.group()
mo3.group(1)

"""**Matching Characters from Alternate Groups**"""

import re
'''
patter = re.compile(r'cat|dog')
mo = patter.search("my  is dog male")
mo.group()'''

pattern = re.compile(r'cat(sit|git|hit)')
mo = pattern.search("my cathit")
mo.group()
mo.group(1)

import re
pattern = re.compile(r'Cat(erpillar|astrophe|ch|egory)')
match1 = pattern.search('Catch me if you can.')
match1.group()

"""**Returning All Matches**"""

import re
#Without_Groups

#pattern = re.compile(r'\d{3}-\d{3}-\d{4}')
#pattern.findall("my num is 123-123-1234 and 321-123-4321")

#Groups

#pattern = re.compile(r'(\d{3}) - (\d{3}) - (\d{4})')
#pattern.findall("my num is 123 - 123 - 4321")

#findall()_doesn't_overlap_matches
patter = re.compile(r'\d{3}')
patter.findall("123")
patter.findall("12345")
patter.findall("123456")