# -*- coding: utf-8 -*-
"""Day-8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19QLP3XyXq2Nt0l2mS3ixbmqqXIu3F-vH

**Mutable_Immutable**
"""

#List Are Mutable
spam = ["cat", "bat", "rat"]
spam[1] = "aardvark"
print(spam)

#String Are Immutable
name = "My name is mehtab"
#name[3] = "k"
print(name)
#Can be did by slicing and assign to new variable
new_name = name[:3] + "k" + name[4:]
print(new_name)

eggs = ['A', 'B', 'C']
eggs = ['x', 'y', 'z']
print(eggs)