# -*- coding: utf-8 -*-
"""Day_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aiLV-zGSR7h3gDATdAgzjkzkoqGk9ZNY

# **Chapter 3 : Loops**

**While And If**
"""

#Both are different on execution

#if program
spam = 0
if spam < 5:
  print('hello world!--if')
  spam = spam + 1

#While use Program
spam = 0
while spam < 5:
  print("hello world! ")
  spam = spam + 1

#Program That Always Ask Name Till Enter Your Name:
Name = ''
while Name != 'your name':
  Name = input("Enter your Name")
print("Thank You!")

"""**Break_Statment**"""

#Program that always run but break at specific
while True:
  Username = input("Enter username: ")
  Password = input("Enter password: ")
  if Username == "mehtab" and Password == "high":
    print("Log in!")
    break
  print("Try Again!")

"""**Continue**"""

while True:
  print("Who are you: ")
  name = input("Name: ")
  if name != "mehtab":
    continue
  print("hello mehtab, Enter your passcode: ")
  passcode = int(input("passcode: "))
  if passcode == 1234:
    print("Access Granted! ")
    break

while True:
    print('Who are you?')
    name = input('>')
    if name != 'Joe':
       continue
    print('Hello, Joe. What is the password? (It is a fish.)')
    password = input('>')
    if password == 'swordfish':
         break
    print('Access granted.')

name = ''
while not name:
    print('Enter your name:')
    name = input('>')
    print('How many guests will you have?')
    num_of_guests = int(input('>'))
    if num_of_guests:
      print('Be sure to have enough room for all your guests.')
    print('Done')

"""**For_Loop**"""

for i in range(1,5):
  print("hello no :" , i)

#Same By Equivalent While loop
i = 1
while i < 5:
  print("iteration is : ", i)
  i = i + 1

#Add all numbers till 100
total = 0
for i in range(101):
  total = total + i
print(total)

#setting start,end,steps
for i in range(1,20,2):
  print("odd iteration is: ", i)
for i in range(0,21,2):
  print("Even iteration is: ", i)

#Use_Negative_Arguments
for i in range(5, -1 , -1):
  print(i)

"""**Importing_Module**"""

'''
import random, sys
for i in range(5):
  print("Random no is: ", random.randint(1,10))
'''
  #Terminate_The_Program_Before_Reach_To_End
import sys
while True:
  Name = input("Enter name: ")
  if Name == "ext":
    sys.exit()
  print("hello" + Name)

"""# **Loops_Real_World_Problems**

**Number_Guessing_Game**
"""

import random
secret_number = random.randint(1,50)
print("Let Play A Number Guessing Game: ")
print("You have 5 Chances Of Guesses! ")
for no_of_guess in range(1,6):
  guess = int(input("Enter Your Guess: "))
  if guess < secret_number:
    print("Guess High!")
  elif guess > secret_number:
    print("Guess Low!")
  else:
    break
if guess == secret_number:
  print("YOU_GUESSED_RIGHT_IN "+ str(no_of_guess)+ " Attempts")
else:
  print("Try next time! OUt of Attempts: ")

import random
secret_number = random.randint(1,10)

Attempts = 0
while guess_num != secret_number:
  Attempts = Attempts + 1
  guess_num = int(input("Enter the num: "))
  if guess_num > secret_number:
   print("guess low")
  elif guess_num < secret_number:
   print("guess high!")
  else:
   print("Right guess!")

"""**Rock_Paper_Scissor_Game**"""

import random, sys

print('ROCK, PAPER, SCISSORS')

# These variables keep track of the number of wins, losses, and ties.
wins = 0
losses = 0
ties = 0

while True:  # The main game loop
    print('%s Wins, %s Losses, %s Ties' % (wins, losses, ties))
    while True:  # The player input loop
        print('Enter your move: (r)ock (p)aper (s)cissors or (q)uit')
        player_move = input('>')
        if player_move == 'q':
            sys.exit()  # Quit the program.
        if player_move == 'r' or player_move == 'p' or player_move == 's':
            break  # Break out of the player input loop.
        print('Type one of r, p, s, or q.')

    # Display what the player chose:
    if player_move == 'r':
        print('ROCK versus...')
    elif player_move == 'p':
        print('PAPER versus...')
    elif player_move == 's':
        print('SCISSORS versus...')

    # Display what the computer chose:
    move_number = random.randint(1, 3)
    if move_number == 1:
        computer_move = 'r'
        print('ROCK')
    elif move_number == 2:
        computer_move = 'p'
        print('PAPER')
    elif move_number == 3:
        computer_move = 's'
        print('SCISSORS')

    # Display and record the win/loss/tie:
    if player_move == computer_move:
        print('It is a tie!')
        ties = ties + 1
    elif player_move == 'r' and computer_move == 's':
        print('You win!')
        wins = wins + 1
    elif player_move == 'p' and computer_move == 'r':
        print('You win!')
        wins = wins + 1
    elif player_move == 's' and computer_move == 'p':
        print('You win!')
        wins = wins + 1
    elif player_move == 'r' and computer_move == 'p':
        print('You lose!')
        losses = losses + 1
    elif player_move == 'p' and computer_move == 's':
        print('You lose!')
        losses = losses + 1
    elif player_move == 's' and computer_move == 'r':
        print('You lose!')
        losses = losses + 1

import random,sys
print("ROCK PAPER SCISSORS")
win = 0
losses = 0
ties = 0
while True:
  print('%s Wins, %s Losses, %s Ties' % (wins, losses, ties))
  while True:
    print("Enter your move: (r)ock (p)aper (s)cissors or (q)uit")
    player_move = input(">")
    if player_move == "q":
      sys.exit()
    if player_move == "p" or player_move == "s" or player_move == "r":
      break
#Display what the player choose
if player_move == "r":
  print("Rock versus...")
elif player_move == "p":
  print("Paper versus...")
elif player_move == "s":
  print("scissor versus...")

#Display what computer choose
move_number = random.randint(1,3)
if move_number == 1:
  computer_move = "r"
  print("Rock")
elif move_number == 2:
  computer_move = "p"
  print("Paper")
elif move_number == 3:
  computer_move = "s"
  print("scissor")

#Display and record the win/loss/tie
if player_move == computer_move:
  print("It is a tie!")
  ties = ties + 1
elif player_move == "p" and computer_move == "r":
  print("You win!")
  win = win + 1
elif player_move == "r" and computer_move == "s":
  print("You win!")
  win = win + 1
elif player_move == "s" and computer_move == "p":
  print("You win!")
  win = win + 1
elif player_move == "r" and computer_move == "p":
  print("you lose!")
  losess = losess + 1
elif player_move == "s" and computer_move == "r":
  print("you lose!")
  losess = losess + 1
elif player_move == "p" and computer_move == "s":
  print("you lose!")
  losess = losess + 1

for i in range(1,10):
  print(i)
i = 0
while i < 11:
  print(i)
  i = i+1