# -*- coding: utf-8 -*-
"""Day-6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zL8vPlZxHxdgbXHGqU4eDZNkLtvndd0c

# **Chapter-6_List**

Problem_Faced
--working_with_list
--input_cat-names_program_modification
--loop_On_list_item_print

Problem_Solved
--divide_Problem_into_Small_Steps
--test_with_different_solution_and_solved_in_last
--try_on_simple_task
"""

#List_Data_Type
name = ["south" , "north", "east", "west"]

#integers
num = [1, 2, 3, 4]

#Mixed_values
mix_num = ['youth' , 33, True, 8.4]

print(num)
print(name)
print(mix_num)

#list_inside_list
list_inside_list = [[1, 2, 3], ["one", "two", "three"]]

#Indexing
print(name[0])
print(mix_num[3])
print(num[-3])
print(list_inside_list)
print(list_inside_list[1])
print(list_inside_list[1][2])

#Slices
value = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print(value[1 : 5])
print(value[ : 6])
print(value[2 : ])
print(value[ : ])
print(value[ : : 2])
print(value[ : : -1])
print(value[ 0: -2 ])

#len()_Function
spam = ["uni", "sin", "hen", "yui"]
print(len(spam))

#Value_update
new_list = ["mehtab", "night", 22, 2.4]
new_list[0] = "ahmad"
new_list[1] = new_list[2]
new_list[0] = new_list[3]
print(new_list)

#Concatenation_Replication
[1, 2, 3, 4] + ["hello", "hi", "uni"]
spam = [1, 3, 5, ]
print(spam + ["rew", "iun", "opi"])
print(spam * 3)

#del_statment
name = ["mehtab", "ahmad", "khan", "south"]
del name[0]
del name[-1]
del name[0:2]
print(name)

"""**Working_With_List**"""

#before
'''
cat_1 = input("Enter first cat_name: ")
cat_2 = input("Enter second cat_ name:")
cat_3 = input("Enter third cat_name: ")
cat_4 = input("Enter fourth cat_name: ")
print([cat_1, cat_2, cat_3, cat_4])
'''
#after
'''
cat_names = []

while True:
  print("Enter name for cat " +str(len(cat_names) + 1) + "Press Enter ext to Stop")
  name = input()
  if name == 'ext':
    break
  cat_names = cat_names + [name]
print("Cats Names are: ")
for name in cat_names:
  print(name)
  '''
cat_names = []
while True:
    print("1. Add  2.Remove 3.ext")
    input_value = int(input("Enter the operation no: "))
    if input_value == 1:
      print("Enter the name of cat: ")
      name = input()
      cat_names = cat_names + [name]
    elif input_value == 2:
      print("Enter the name of cat to remove: ")
      name = int(input())
      del cat_names[name]
    elif input_value == 3:
      break

for name in cat_names:
  print(' '+ name)

"""**For_Loop_In_List**"""

#Normal_For_loop
for i in range(5):
  print(i, end = " ")

#For_Loop_Use_List
for i in [1 , 2 , 3, 4]:
  print(i)

spam = [1, 2, 3, 4, 5]
for i in range(len(spam)):
  print("Value at " + str(i) + " is " + str(spam[i]))

supplies = ['pens', 'staplers', 'flamethrowers', 'binders']
for i in range(len(supplies)):
  #print("index : " + str(i) + " is " + str(supplies[i]))
  print("index" + str(i))
  print("item at " + str(i) + "is " + str(supplies[i]))

"""**In_Not-In_operator**"""

spam = ["mehtab" ,"ahmad", "khan"]
print("mehtab" in spam)
print("khan" not in spam)

#program to check name in list
spam = ["mehtab" ,"ahmad", "khan"]

while True:
 name = input("dnter the name: ")
 if name in spam:
  print("Present!")
  break
 else:
  print("Absent!")

"""**Multiple_Assignment_Tricks**"""

names = ["mehtab", "ahmad", "khan"]
first_name = names[0]
second_name = names[1]
third_name = names[2]
print(first_name)
print(second_name)
print(third_name)

spam = ["mehtab", "ahmad", "khan"]
first_name, second_name, third_name = spam
print(first_name)
print(second_name)
print(third_name)

#Enumerate()_Function
supplies = ["pin", "rubber", "rig"]
for index, item in enumerate(supplies):
  print("index is :" + str(index) + " item is : " + item)

"""spam"""

