# -*- coding: utf-8 -*-
"""Day-5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Iu4ZuljXL8q9dmPaqJU7JyweNM_NKNd0

# Chapter-5_Debugging

### #Problem_faced
-confusing exception,assertion,logging
-Coin_flip_Program_Debugging

### #Problem_Solved
-search on browner and understand by example
-Debugging_Done_By_Changing_str-int_in_input

**Raise_An_Exception**
"""

#program for no number below xero
#num = input("Enter number")
#if num < 0:
   # raise Exception("no number below zero")

#program for not other than integer
num = input("Enter number")
if not type(num) is int:
    raise Exception("should be integer")

def box_print(symbol, width, height):
    if len(symbol) != 1:
       raise Exception('Symbol must be a single character string.')
    if width <= 2:
       raise Exception('Width must be greater than 2.')
    if height <= 2:
       raise Exception('Height must be greater than 2.')

    print(symbol * width)
    for i in range(height - 2):
        print(symbol + (' ' * (width - 2)) + symbol)
    print(symbol * width)

try:
    box_print('*', 4, 4)
    box_print('O', 20, 5)
    box_print('x', 1, 3)
    box_print('ZZ', 3, 3)
except Exception as err:
    print('An exception happened: ' + str(err))
try:
    box_print('ZZ', 3, 3)
except Exception as err:
    print('An exception happened: ' + str(err))

import time
def boc_print(symbol, width, height):
  if len(symbol) != 1:
    raise Exception("Symbol must be single character!")
  if width <= 2:
    raise Exception("Width should be greater than 2!")
  if height <= 2:
    raise Exception("height should be greater than 2!")

  print("*" * width)
  for i in range(height - 2):
   print(symbol + (' ' * (width - 2)) + symbol)
   time.sleep(2)
  print("*" * width)

try:
  boc_print("&" ,4 ,4)
  boc_print("&" ,10 ,4)
except Exception as err:
  print("An exception happened: " + str(err))

"""**Assert_Statment**"""

#using assert to know code execute right
age = [111,2,3,32,33,22,52]
age.sort()
print(age)
assert age[0] <= age[-1]

#if we reverse it
age.reverse()
print(age)
assert age[0] <= age[-1]

"""**The_Logging**"""

import logging
logging.basicConfig(level=logging.DEBUG, format=' %(asctime)s -  %(levelname)s -  %(message)s')
logging.debug("Start of Program")

def factorial(n):
  logging.debug("Start of factorial " + str(n))
  total = 1
  for i in range(n+1):
    total *= i
    logging.debug("i is "+ str(i) + ", total is " + str(total))
  logging.debug("End of factorial" + str(n))
  return total
print(factorial(5))
logging.debug("End of program")

#changing for i in range(1, n+1)
import logging
logging.basicConfig(level=logging.DEBUG, format='%(asctime)s -  %(levelname)s -  %(message)s')
logging.debug('Start of program')

def factorial(n):
    logging.debug('Start of factorial(' + str(n) + ')')
    total = 1
    for i in range(1,n + 1):
        total *= i
        logging.debug('i is ' + str(i) + ', total is ' + str(total))
    logging.debug('End of factorial(' + str(n) + ')')
    return total

print(factorial(5))
logging.debug('End of program')

import logging
logging.basicConfig(filename='myProgramLog.txt', level=logging.DEBUG,
format=' %(asctime)s -  %(levelname)s -  %(message)s')

import logging
logging.basicConfig(level=logging.DEBUG)

logging.debug('This is a debug message, and it will be displayed.')

#Before
'''
import random
guess = ''
while guess not in ('heads', 'tails'):
    print('Guess the coin toss! Enter heads or tails:')
    guess = input()
toss = random.randint(0, 1)  # 0 is tails, 1 is heads
if toss == guess:
    print('You got it!')
else:
    print('Nope! Guess again!')
    guess = input()
    if toss == guess:
        print('You got it!')
    else:
        print('Nope. You are really bad at this game.')
'''

#After
import random

guess = ''
while guess not in ('heads', 'tails'):
    print('Guess the coin toss! Enter heads or tails:')
    guess = input()

# Map the random integer to a string value
toss_int = random.randint(0, 1)  # 0 or 1
if toss_int == 0:
    toss = 'tails'
else:
    toss = 'heads'

if toss == guess:
    print('You got it!')
else:
    print('Nope! Guess again!')
    guess = input()
    if toss == guess:
        print('You got it!')
    else:
        print('Nope. You are really bad at this game.')