# -*- coding: utf-8 -*-
"""Day-4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ryoFnFcj104lOgCwMcPIqIhEoHFkptXN

# Chapter-4_Functions

**Creating_Function**
"""

#Create simple function
def  greet():
  #print three times
  print("hello buddy")
  print("hello good morning")
greet()
greet()
print("one more time")
greet()

"""**Arguments_Parameters**"""

#passing values to function
def hello_greet(name):
  print("hello "+ name)
  print("how are you " + name)
hello_greet("mehtab")
hello_greet("sameee")

"""**Return_values**"""

import random

def get_answer(answer_no):
  if answer_no == 1:
    print("Monday")
  elif answer_no == 2:
    print("tuesday")
  elif answer_no == 3:
    print("wednesday")
  elif answer_no == 4:
    print("thursday")
  elif answer_no == 5:
    print("friday")

print("Enter no between 1 - 5: ")
input(" > ")
r = random.randint(1,5)
get_answer(r)

"""**Named_Parameter**"""

#Change_End/Sep_default_To_Anything_else
print("hello",end = ' ')
print("world")


#flipcoin.py

import random
for i in range(10):
  if random.randint(0,1) == 0:
    print("H",end = ' ')
  else:
    print("T" , end = ' ')
print()

#change sep
print("hello","world" )
print("ehllo ", "buddy" , sep = '+ ')

def a():
    print('a() starts')
    b()
    d()
    print('a() returns')

def b():
    print('b() starts')
    c()
    print('b() returns')

def c():
    print('c() starts')
    print('c() returns')

def d():
    print('d() starts')
    print('d() returns')
a()

"""**Global_Local_Scope**"""

#Glocal scope can't use local scope
'''
def spam():
  eggs = "mehtab"
spam()
print(eggs)


#local scope can't use in other local scope
def spam():
  eggs = "mehtab"
  sih()
  print(eggs)
def sih():
  eggs = "ahmad"
  print(eggs)
spam()
'''
#Global_Statement
def spam():
  #global greet #became global by default it is local acces within function
  greet = "hello world"
  print(greet)

greet = "mehtab"
print(greet)
spam()
print(greet)

"""**Exception_Handling**"""

def div(num):

  try:
     return 22 / num
  except ZeroDivisionError:
    print("invalid! argument...")
print(div(2))
print(div(4))
print(div(0))
print(div(8) )

#Another_Way_Of_Execution
def div2(num):
  return 33 / num

try:
  print(div(2))
  print(div(4))
  print(div(0))
  print(div(8) )
except ZeroDivisionError:
    print("invalid! argument...")

"""# Real_World_Programs

**Zig-Zag_Program**
"""

import time, sys
indent = 0  # How many spaces to indent
indent_increasing = True  # Whether the indentation is increasing or not

try:
    while True:  # The main program loop
        print(' ' * indent, end='')
        print('********')
        time.sleep(0.5) # Pause for 1/10th of a second.

        if indent_increasing:
            # Increase the number of spaces:
            indent = indent + 1
            if indent == 20:
                # Change direction:
                indent_increasing = False
        else:
            # Decrease the number of spaces:
            indent = indent - 1
            if indent == 0:
                # Change direction:
                indent_increasing = True
except KeyboardInterrupt:
    sys.exit()

import sys, time
indent = 0
indent_increasing = True
try:
    while True:
        print(' ' * indent, end='')
        print('*')
        time.sleep(0.7)
        if indent_increasing:
            indent = indent + 1
            if indent == 3:
                indent_increasing = False
        else:
          indent = indent - 1
          if indent == 0:
            indent_increasing = True
except KeyboardInterrupt:
  sys.exit()

"""**Spikes_Animation**"""

import sys, time
indent = 0
indent_increasing = True
try:
    while True:
      for i in range(1,5):
        print("-" * (i * i))
        time.sleep(0.5)
      for i in range(5,1,-1):
        print("-" * (i * i) )
        time.sleep(0.5)
except KeyboardInterrupt:
  sys.exit()

"""D**ice_Rolling_program**"""

import random
random_number = random.randint(1, 6)

def get_random_dice_roll():
    # Returns a random integer from 1 to 6
    return random_number

print(get_random_dice_roll())
print(get_random_dice_roll())
print(get_random_dice_roll())
print(get_random_dice_roll())

"""T**he Collatz Sequence**"""

def collatz(number):
  try:
    if number % 2 == 0:
      return number // 2
    elif number % 2 == 1:
      return 3 * number + 1
  except ValueError:
    print("Enter valid number")
collatz(1)