# -*- coding: utf-8 -*-
"""Day-10_Dictionaries.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LY7F5tElCKR0Tee2pAjRtr-tE7_y-zgj

**Returning_Key_Values**
"""

#Return_Keys

spam = {"name" : "metab", "age": 21, "gender": "male"}
for i in spam.keys():
  print(i)

#Return_Values
for v in spam.values():
  print(v)

#Return key_Value_Pair
for j in spam.items():
  print(j)

#In_And_Not-In
"name" in spam.keys()
"metab" not in spam.values()
"age" , 21 in spam.items()

#Printing_All_Keys

print(spam.keys() )
print(list(spam.keys()))

#Multiple_Assignment_Trick

for k, v in spam.items():
  print("Key: " + k + " Value: " + str(v))

"""**Checking Whether a Key Exists**"""

names = {1 : "mehtab", 2: "saood" , 3: "rafis"}
print(names.get(4 , "unknown"))
print(names.get(1 , "unknown"))

"""**Setting Default Values**"""

# With_built-in-Function
num = {"one": 1, "two": 2, "three": 3}
num["two"] = num["one"]
del num["one"]
print(num)
if "four" not in num:
  num["four"] = 4
  print(num)

#Setdefault() Function
num.setdefault("five" , 5)
print(num)
num.setdefault("five" , 10)
print(num)

"""**Character_Count_Program**"""

message = "My naMe is mehtab i am twelve year old i am a student"
count = {}
for character in message:
  count.setdefault(character , 0)
  count[character] = count[character] + 1
print(count)

from typing_extensions import is_protocol
import sys, copy

STARTING_PIECES = {'a8': 'bR', 'b8': 'bN', 'c8': 'bB', 'd8': 'bQ',
'e8': 'bK', 'f8': 'bB', 'g8': 'bN', 'h8': 'bR', 'a7': 'bP', 'b7': 'bP',
'c7': 'bP', 'd7': 'bP', 'e7': 'bP', 'f7': 'bP', 'g7': 'bP', 'h7': 'bP',
'a1': 'wR', 'b1': 'wN', 'c1': 'wB', 'd1': 'wQ', 'e1': 'wK', 'f1': 'wB',
'g1': 'wN', 'h1': 'wR', 'a2': 'wP', 'b2': 'wP', 'c2': 'wP', 'd2': 'wP',
'e2': 'wP', 'f2': 'wP', 'g2': 'wP', 'h2': 'wP'}

BOARD_TEMPLATE = """
    a    b    c    d    e    f    g    h
   ____ ____ ____ ____ ____ ____ ____ ____
  ||||||    ||||||    ||||||    ||||||    |
8 ||{}|| {} ||{}|| {} ||{}|| {} ||{}|| {} |
  ||||||____||||||____||||||____||||||____|
  |    ||||||    ||||||    ||||||    ||||||
7 | {} ||{}|| {} ||{}|| {} ||{}|| {} ||{}||
  |____||||||____||||||____||||||____||||||
  ||||||    ||||||    ||||||    ||||||    |
6 ||{}|| {} ||{}|| {} ||{}|| {} ||{}|| {} |
  ||||||____||||||____||||||____||||||____|
  |    ||||||    ||||||    ||||||    ||||||
5 | {} ||{}|| {} ||{}|| {} ||{}|| {} ||{}||
  |____||||||____||||||____||||||____||||||
  ||||||    ||||||    ||||||    ||||||    |
4 ||{}|| {} ||{}|| {} ||{}|| {} ||{}|| {} |
  ||||||____||||||____||||||____||||||____|
  |    ||||||    ||||||    ||||||    ||||||
3 | {} ||{}|| {} ||{}|| {} ||{}|| {} ||{}||
  |____||||||____||||||____||||||____||||||
  ||||||    ||||||    ||||||    ||||||    |
2 ||{}|| {} ||{}|| {} ||{}|| {} ||{}|| {} |
  ||||||____||||||____||||||____||||||____|
  |    ||||||    ||||||    ||||||    ||||||
1 | {} ||{}|| {} ||{}|| {} ||{}|| {} ||{}||
  |____||||||____||||||____||||||____||||||
"""
WHITE_SQUARE = '||'
BLACK_SQUARE = '  '

def print_chessboard(board):
  square = []
  is_white_square = True
  for y in "87654321": #8
    for x in "abcdefgh": #a---b
      print(x, y, is_white_square) #(a,8,True)--------------------------------(b,8,True)
      if x + y in board.keys(): # a8 in board.keys---- True ------------------b8 in board.keys---- True
        square.append(board[x + y]) #[].add("bR")-----------------------------#[].add("bN")
      else:
        if is_white_square: # True.add(||)
          square.append(WHITE_SQUARE)
        else:               #False.add(" ")-----------------------------------#False.add(" ")
          square.append(BLACK_SQUARE)
      is_white_square = not is_white_square # is_White_Square == False-------- is_White_Square == True
    is_white_square = not is_white_square

"""**Chess_Board_Program**"""

import sys, copy

STARTING_PIECES = {'a8': 'bR', 'b8': 'bN', 'c8': 'bB', 'd8': 'bQ',
'e8': 'bK', 'f8': 'bB', 'g8': 'bN', 'h8': 'bR', 'a7': 'bP', 'b7': 'bP',
'c7': 'bP', 'd7': 'bP', 'e7': 'bP', 'f7': 'bP', 'g7': 'bP', 'h7': 'bP',
'a1': 'wR', 'b1': 'wN', 'c1': 'wB', 'd1': 'wQ', 'e1': 'wK', 'f1': 'wB',
'g1': 'wN', 'h1': 'wR', 'a2': 'wP', 'b2': 'wP', 'c2': 'wP', 'd2': 'wP',
'e2': 'wP', 'f2': 'wP', 'g2': 'wP', 'h2': 'wP'}

BOARD_TEMPLATE = """
    a    b    c    d    e    f    g    h
   ____ ____ ____ ____ ____ ____ ____ ____
  ||||||    ||||||    ||||||    ||||||    |
8 ||{}|| {} ||{}|| {} ||{}|| {} ||{}|| {} |
  ||||||____||||||____||||||____||||||____|
  |    ||||||    ||||||    ||||||    ||||||
7 | {} ||{}|| {} ||{}|| {} ||{}|| {} ||{}||
  |____||||||____||||||____||||||____||||||
  ||||||    ||||||    ||||||    ||||||    |
6 ||{}|| {} ||{}|| {} ||{}|| {} ||{}|| {} |
  ||||||____||||||____||||||____||||||____|
  |    ||||||    ||||||    ||||||    ||||||
5 | {} ||{}|| {} ||{}|| {} ||{}|| {} ||{}||
  |____||||||____||||||____||||||____||||||
  ||||||    ||||||    ||||||    ||||||    |
4 ||{}|| {} ||{}|| {} ||{}|| {} ||{}|| {} |
  ||||||____||||||____||||||____||||||____|
  |    ||||||    ||||||    ||||||    ||||||
3 | {} ||{}|| {} ||{}|| {} ||{}|| {} ||{}||
  |____||||||____||||||____||||||____||||||
  ||||||    ||||||    ||||||    ||||||    |
2 ||{}|| {} ||{}|| {} ||{}|| {} ||{}|| {} |
  ||||||____||||||____||||||____||||||____|
  |    ||||||    ||||||    ||||||    ||||||
1 | {} ||{}|| {} ||{}|| {} ||{}|| {} ||{}||
  |____||||||____||||||____||||||____||||||
"""
WHITE_SQUARE = '||'
BLACK_SQUARE = '  '

def print_chessboard(board):
    squares = []
    is_white_square = True
    for y in '87654321':
        for x in 'abcdefgh':
            print(x, y, is_white_square)  # DEBUG: Show coordinates
            if x + y in board.keys():
                squares.append(board[x + y])
            else:
                if is_white_square:
                    squares.append(WHITE_SQUARE)
                else:
                    squares.append(BLACK_SQUARE)
            is_white_square = not is_white_square
        is_white_square = not is_white_square

    print(BOARD_TEMPLATE.format(*squares))


print('Interactive Chessboard')
print('by Al Sweigart al@inventwithpython.com')
print()
print('Pieces:')
print('  w - White, b - Black')
print('  P - Pawn, N - Knight, B - Bishop, R - Rook, Q - Queen, K - King')
print('Commands:')
print('  move e2 e4 - Moves the piece at e2 to e4')
print('  remove e2 - Removes the piece at e2')
print('  set e2 wP - Sets square e2 to a white pawn')
print('  reset - Resets pieces back to their starting squares')
print('  clear - Clears the entire board')
print('  fill wP - Fills entire board with white pawns.')
print('  quit - Quits the program')

main_board = copy.copy(STARTING_PIECES)
while True:
    print_chessboard(main_board)
    response = input('> ').split() #move e2 e4---("move" , "e2" , "e4")
    if response[0] == 'move':
        main_board[response[2]] = main_board[response[1]] # e4 = e2
        #main_board["e4"] = main_board["e2"]
        del main_board[response[1]]
    elif response[0] == 'remove':
        del main_board[response[1]]
    elif response[0] == 'set':
        main_board[response[1]] = response[2]
    elif response[0] == 'reset':
        main_board = copy.copy(STARTING_PIECES)
    elif response[0] == 'clear':
        main_board = {}
    elif response[0] == 'fill':
        for y in '87654321':
            for x in 'abcdefgh':
                main_board[x + y] = response[1]
    elif response[0] == 'quit':
        sys.exit()

"""**Nested Dictionaries and Lists**"""

spam = {"mehtab" : {"age" : 11, "gender" : "M"} , "saood" : {"age" : 12, "gender" : "M"}}
num = 0
for k, v in spam.items():
  num = num + v.get("M" , 0)
print(num)

"""**Program_For_Printing_Repition**"""

all_guests = {'Alice': {'apples': 5, 'pretzels': 12},
              'Bob': {'ham sandwiches': 3, 'apples': 2},
              'Carol': {'cups': 3, 'apple pies': 1}}

def total_brought(guests, item):
    num_brought = 0
    for k, v in guests.items():
       num_brought = num_brought + v.get(item, 0)
    return num_brought

print('Number of things being brought:')
print(' - Apples         ' + str(total_brought(all_guests, 'apples')))
print(' - Cups           ' + str(total_brought(all_guests, 'cups')))
print(' - Cakes          ' + str(total_brought(all_guests, 'cakes')))
print(' - Ham Sandwiches ' + str(total_brought(all_guests, 'ham sandwiches')))
print(' - Apple Pies     ' + str(total_brought(all_guests, 'apple pies')))

#Try_Myself
all_guest = {"Mehtab": {"apple" : 33 , "cups" : 1},
             "saood" : {"cups": 2, "units": 9}}
def products(guest , item):
  num = 0
  for k, v in guest.items():
    num = num + v.get(item,0)
  return num
print("Program To Show The Occurance: ")
print("-       Apples             " + str(products(all_guest , "cups")))



"""**Exercise_Question**"""

#Q-1
spam = {}
print(spam)
print(type(spam))

#Q-2
spam1 = {"foo": 42}
print(spam1)
print(type(spam1))
if 'color' not in spam:
    spam['color'] = 'black'
print(spam)
spam.setdefault("color" , "white")
print(spam)
spam.setdefault("color" , "pink")
print(spam)
if 'color' not in spam:
    spam['color'] = 'pink'
print(spam)

import pprint

my_dictionary = {
    'name': 'John Doe',
    'age': 30,
    'occupation': 'Software Developer',
    'skills': ['Python', 'JavaScript', 'SQL', 'DevOps'],
    'address': {
        'street': '123 Main St',
        'city': 'Anytown',
        'zipcode': '12345'
    }
}

print("--- Standard print() output ---")
print(my_dictionary)


print("\n--- pprint.pprint() output ---")
pprint.pprint(my_dictionary, indent=4)

pretty_string = pprint.pformat(my_dictionary, indent=4)
print("\n--- pformat() output stored as a string ---")
print(pretty_string)

#Try_myself

intro = {

    'name': 'John Doe',
    'age': 30,
    'occupation': 'Software Developer',
    'skills': ['Python', 'JavaScript', 'SQL', 'DevOps'],
    'address': {
        'street': '123 Main St',
        'city': 'Anytown',
        'zipcode': '12345'
    }
}
print(intro)
pprint.pprint(intro, indent = 4)

"""# **Easy_Problems**"""

#Creating Dictionary of 5 Student And Marks
Students = {
    "mehtab" : 33,
    "saood" : 33,
    "rafiq" : 77,
    "ali" : 99,
    "hameed" : 33
}
print(Students)

#Print_Key and Values

print(Students.keys())
print(Students.values())

#Check_If_Key_is_Exist_in_Dictionary

if "ali" in Students.keys():
  print("yes")
else:
  print("no")

if 33 in Students.values():
  print("yes")
else:
  print("no")

#Count_Frequency_Character
import time
string1 = "my naem is mehtab khan"
count = {}

for character in string1:

  #First_Approach----------
  count.setdefault(character , 0)
  count[character] = count[character] + 1

  #Second_Approach----------
  #count[character] = count.get(character,0) + 1

print(count)

#Words_Frequency_Character
string2 = "My name is sheema and i amd i student"
slpit_word = string2.lower().replace("."," ").split()

word_count = {}

for word in slpit_word :
  word_count.setdefault(word , 0)
  word_count[word] = word_count[word] + 1

print(word_count)