# -*- coding: utf-8 -*-
"""Day-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L1TKfri7mzXZv2gExXqlKUB416HV7aFa

# **Chapter 2- IF_ELSE AND fLOW** **CONTROL**

**Bolean Values,Comparison,Bolean** **Operator**
"""

#Bolean Values

me = True
False_value = False
print(me)
print(False_value)
me = False_value
print(me)

#Comparison Operators

print(10 > 11)
print('a' > 'b')
print(10 == 12)
print(10 >= 10)
print( 7 <= 7)
print(1 != 1)
print("hello" == "hello")
print("cat " != "dog")

#Bolean Operator

#and operator
print(True and True)
print(False and True)
print(False and False)
print(True and False)
#or operator
print(True or True)
print(False or True)
print(False or False)
print(True or False)
#not operator
print(not True)
print(not False)

#Mixing Bolean and Comparison Operator
print((2 > 1) and (3 > 2))
print((2+2 == 4) and (2 * 2 == 4) and (8 / 2 != 8))

"""**If_Else,elif**"""

#if
'''
name = str(input("enter the name > "))
if name == "mehtab":
  print("hello , mehtab!")
#else
else:
  print("hello, buddy")

# Password_username_Program
username = input("Enter username: ")
if username == "mehtab":
  password = input("Enter password: ")
  if password == "19141":
    print("Access granted")
  else:
    print("Wrong password")
else:
  print("Wrong username")

#elif_Program
name = input("Enter name: ")
age = int(input("Enter age: "))
if name == "mehtab":
  print("hello mehtab!")

elif age < 18:
  print("he mehtab")
else:
  print("someone else!")
'''
print('Enter TB or GB for the advertised unit:')
unit = input('>')

# Calculate the amount that the advertised capacity lies:
if unit == 'TB' or unit == 'tb':
    discrepancy = 1000000000000 / 1099511627776
elif unit == 'GB' or unit == 'gb':
    discrepancy = 1000000000 / 1073741824

print('Enter the advertised capacity:')
advertised_capacity = input('>')
advertised_capacity = float(advertised_capacity)

# Calculate the real capacity, round it to the nearest hundredths,
# and convert it to a string so it can be concatenated:
real_capacity = str(round(advertised_capacity * discrepancy, 2))

print('The actual capacity is ' + real_capacity + ' ' + unit)

"""# **If_Else_Real_World_Problems**

**Tax_Calculator**
"""

income = float(input("Enter the annual income: "))
if income <= 250000:
  print("NO! Zero TAX")
elif 250001 < income < 500000:
  print("Total Tax is: ", (income - 250000) * 0.5 )
else:
  print("Total Tax is : ", (income - 500000) * 0.10 + 12500)

"""**User_Input_Validation**"""

#Program For User Input Name IF IT Start With Vowel Should Print Or Otherwise Consonant
'''
Name = input("Enter Your Name: ")
if Name[0] in "aeiouAEIOU":
  print("Start With Vowel")
else:
  print("Start With Consonant")
  '''
#Program run 3Times
'''
i = 3
while i != 0:
  Name = input("Enter Your Name: ")
  if Name[0] in "aeiouAEIOU":
    print("Start With Vowel")
  else:
    print("start with consonant")
  i = i - 1
'''
#program print ends with vowel or consonant
'''
Name = input("Enter Name: ")
if Name[-1].lower() in "aeiou":
  print("Name Ends With Vowel")
else:
  print("Ends With Consonant")
'''
#Program for Name Ends And Start With Vowel

Name = input("Enter YOur Name:")
if Name[0].lower() and Name[-1].lower() in "aeiou":
  print("Start And Ends With Vowel")
elif Name[0].lower() and Name[-1].lower() not in "aeiou":
  print("Start And Ends With Consonant")
elif Name[0].lower() in "aeiou":
  print("Start with vowel")
elif Name[0].lower() not in "aeiou":
  print("Start with Consonant")
elif Name[-1].lower() in "aeious":
  print("Ends with Vowel")
elif Name[-1].lower() not in "aeious":
  print("Ends with Consonant")
else:
  print("No vowel and consonant at Strt and end")

""" **Automated Data Processing Logic (if inside a for loop)**"""

#iterate on Data And Apply Constraits By Skipping And Stopping On Specific Values
Number = [100, 200,300,400,500,600,700]
for num in Number:
  if num >= 400 and num <= 600:
    print("Value is Too High!" , num)
    continue
  elif num[2] == 300:
    print("number is 300")
    continue
  elif num < 150:
    print("Value is Too Small" , num)
    continue
  print("Processing!",num)

"""Nested Conditional Logic (Ticket Pricing)"""

Age = int(input("Enter The Age: "))
Gender = input("Enter The Gender: ")

if Age > 60:
  if Gender == "f":
    print("50% Discount")
  else:
    print("10% Discount")
else:
  print("Full Pay!")

"""**Ternary Operator**"""

Score = 33
result = "pass" if Score >= 33 else "fail"
print(result)

"""# **W3School_Python**

**Variables**
"""

#Creating Variables
a = 4
b = "mehatb"
c = 4.3
print(a,b,c)

#Casting
a = int('3')
b = float('4.3')
c = str(5)
print(a,b,c)

#Variable_Names
#Start with num or hyphen,special character only



