# -*- coding: utf-8 -*-
"""Day-11_Strings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Yq1-9sSNi_q51q421P8NTxuskf6__4d

# Strings_And_Methods

**String_Escape-Sequence**
"""

Str1 = "My name is mehtab"
print(Str1)

Str1 = "My name is \"Mehtab\""
print(Str1)

Str1 = "my name is \n mehtab \t and i\'m the best "
print(Str1)

#Raw_String
str2 = r"my name is \n mehtab \t and i\'m the best "
print(str2)

#multiline_String

str2 = """
my nais mehtab
ahmd
khan
"""
print(str2)

#multiline_Comment

"""my name is mehta
khan
khan"""

"""**Indexing_Slicing**"""

name = "Hello_World!"
print(name[0])
print(name[5])
print(name[:6])
print(name[:-1])

new_name = name[0 : 5]
print(new_name)

"""**In_And_Not-IN_MEthod**"""

spam = "mehtab ahmad khan"
"khan" in spam
"ahmad" not in spam

"""**f-String**"""

#First_Manual_Method
spam = "mehtab"
Gender = "Male"
print("my brother name is " + spam + " and he is "  + Gender )

#Using_F_Method
spam = "mehtab"
age = 33
print(f"my name is {spam} and i {age} year old..")

#Old_Method
#%s_method
spam = "mehtab"
age = 33
print("my name is %s and i am %s year old" % (spam, age))
print("and i will be %s in next ten year" % (age + 10 ))

#Format_method
spam = "mehtab"
age = 23
print("my name is {} and i am {} year old, ".format(spam,  age))

#use the index
print("my brother name is {0} and his other cxn name is also {0}".format(spam, age))

"""# **Strings_Method**

**Change_Case**
"""

spam = "my Name Is Mehtab"
print(spam.lower()) # Cannot changing original string
print(spam)
print(spam.upper())
print(spam)
new_spam = spam.upper()
print(new_spam)

if spam.lower() == "my name is mehtab":
    print("True")
else:
    print("False")

#islower()_And_islower()
new_spam.islower()
new_spam.lower().islower()
"1234567".isupper()

#Other_Methods
print("These_Are_String_Methods.")
print("mehtab".isalpha())
print("1234".isalpha())
print("mehtab khan".isalpha())
print("mehtab1122".isalnum())
print("mehtab 1122".isalnum())
print("123456".isalnum())
print("aserty".isalnum())
print("234567".isdecimal())
print("123 123".isdecimal())
print("11.11".isdecimal())
print(" ".isspace())
print("\n".isspace())
print("\t".isspace())
print("".isspace())
print("mehtab".istitle())
print("Mehtab".istitle())
print("Mehtab Khan".istitle())
print("Mehtab khan".istitle())

#Program_For_User-Input

while True:
    print("Enter your age:")
    age = input()
    if age.isdecimal():
      break
    print("Enter a valid number: ")
while True:
  print("Enter new password (alphabet + numbers ):   ")
  passcode = input()
  if passcode.isalnum():
    break
  print("Enter a valid passcode!")
print("Now ! You can log_in!")

"""Start-End_With_Methods"""

spam = "Mehtab"
print(spam.startswith("M"))

print(spam.endswith("b"))

print(spam.startswith("Mehtab"))

print(spam.endswith("Mehtab"))

num = "23456"

print(num.startswith("2"))

print(num.endswith("6"))

"""Join_Split_Method"""

spam = ["me", "is", "back"]

" ".join(spam)
" ,".join(spam)
"abc".join(spam)

#split()
spam = "my name is mehtab"
spam.split()
spam.split("m")
spam.split("")

"""Justifying_Center_Method"""

spam = "mehtab"
print(spam.rjust(10))
print(spam.ljust(10))
print("hello".rjust(15))
print("hello".ljust(15))

#Another_Argument
print(spam.rjust(20 , "="))
print(spam.ljust(20 , "="))

#Center_Method
print(spam.center(20))
print(spam.center(20,"$"))

"""**Removing_Spaces**"""

spam = "         -----mehmtamb-----            "
print(spam.rstrip())
print(spam.lstrip())
print(spam.strip())
spam1 = "shimehshimehshimehshi"
print(spam1.strip('shi'))
spam2 = 'SpamSpamBaconSpamEggsSpamSpam'
spam2.strip('ampS')

"""**Numeric_Code_Points_Character**"""

ord("A")
chr(65)
chr(ord("b"))
chr(ord("b") + 1)

"""Copying_Pasting"""

import pyperclip
pyperclip.copy("hello world")
pyperclip.paste()

def printTable(tableData):
    # Create a list containing the same number of 0s as the number of inner lists
    colWidths = [0] * len(tableData)

    # Find the longest string in each inner list
    for i in range(len(tableData)):
        for item in tableData[i]:
            if len(item) > colWidths[i]:
                colWidths[i] = len(item)

    # Display the table, iterating through rows first
    # (assuming all inner lists are the same length)
    for row in range(len(tableData[0])):
        for col in range(len(tableData)):
            # Right-justify the string using the pre-calculated column width
            print(tableData[col][row].rjust(colWidths[col]), end=' ')
        print() # Print a newline after each row

# Example usage
tableData = [['apples', 'oranges', 'cherries', 'banana'],
             ['Alice', 'Bob', 'Carol', 'David'],
             ['dogs', 'cats', 'moose', 'goose']]

printTable(tableData)