# -*- coding: utf-8 -*-
"""Day-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DL52OfnH6W_PBJnTQTv8dzzhlM8ol4_Q
"""

print("hello world")

"""**Variable and Comment**"""

#variable
num = 44
name = "mehtab"
print(num)

#Casting -- specify data type of a number
num = int('3')
print(num)

name = str(19141)
print(name)

float_num = float(3)
print(float_num)

#Type Function

print(type(num))
print(type(name))
print(type(float_num))

#use of semicolon "" or ''
print("hello world")
print('hello world')

#Case sensitive
num = 1
Num = 2
NUM = 3
NuM = 4
print(num) # These are four variables

#Comments
#this is the first day of learning python

#single_line_comment
"""
this multiline
line
comments
"""
print("hello")

"""**Statements**"""

#set of instruction are computer program
print("hello")
print("mehtab")

#Semicolon
print("hello");print("mehtab")

#error by using print two time without semicolon
#print(33) print(44)

"""**Outputs**"""

#print()
print(33)
print("mehtab")

#without using "" will give error
#print(the is not iu)

#Number
print(33)
print(4.4)

#Maths
print(44+4)
print(2*7)

#text + number
print("i am " , 4 , "years old")

print('Hello, world!')
print('What is your name?')  # Ask for their name.
my_name = input('>')
print('It is good to meet you, ' + my_name)
print('The length of your name is:')
print(len(my_name))
print('What is your age?')  # Ask for their age.
my_age = input('>')
print('You will be ' + str(int(my_age) + 1) + ' in a year.')

print("What is your name: ")
name = input()
print("nice to meet you,", name)
print("lenght of your name is: ", len(name))
print("What Is Your Age: ")
age = input()
print("your age is ", age ,  "And you will be " + str(int(age)+1)+ " next year..")

"""
## **Type Function**"""

type(42)
type(5.5)
type(True)
type("mehtab")
type(len("mehtab"))

"""# **Round ,Abs ,bin, hex** **Function**"""

round(2.2)
round(3.5) #number with end .5 is rounded to the nearest even number.
round(2.5)
abs(-22)
abs(-2.13)
abs(44)
print("i eat  " + str(4) + "  bananas yesterday")
bin(4)[2:]
hex(4)

"""# 1-Project_File_Rename_Using_Python"""

import os
i = 0
path = os.chdir("C:\\Users\\AZAN COM\\OneDrive\\Desktop\\New folder")
for file in os.listdir(path):
  new_file = "gfg_pic{}.png".format(i)
  os.rename(file,new_file)
  i + 1